backend:
  name: git-gateway
  branch: main
media_folder: src/assets
public_folder: /assets

collections:
  - label: Sections
    name: sections
    folder: src/sections
    create: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Contact Message, name: contactMessage, widget: text }
  - label: Activities
    name: activities
    folder: src/activities
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Short Title, name: shortTitle, widget: string, description: Use lower case, one word. }
      - { label: Summary, name: summary, widget: text, description: One sentence summary for SEO. }
      - { label: Order, name: order, widget: number }
  - label: Slider Images
    name: sliderImages
    folder: src/slider-images
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Image, name: img, widget: image }
      - { label: Order, name: order, widget: number }
  - label: Settings
    name: settings
    files:
      - label: Meta Settings
        name: metaSettings
        file: src/_data/site.json
        fields:
          - { label: Site Name, name: name, widget: string }
          - { label: Site Tagline, name: subtitle, widget: string }
          - { label: Meta Title, name: metaTitle, widget: string }
          - { label: Meta Description, name: metaDescription, widget: text }
          - { label: Open Graph Image, name: openGraphImage, widget: image }
          - { label: Canonical URL, name: url, widget: string }
          - { label: Favicon, name: favicon, widget: image }
          - label: Social Links
            name: socialLinks
            widget: list
            fields:
              - { label: App Name, name: name, widget: string }
              - { label: Profile Link, name: url, widget: string }
              - { label: Icon Name, name: icon, widget: string, description: Lower case app name }
          - label: Colophon
            name: colophon
            widget: object
            fields:
              - { label: Headings Font, name: headings, widget: string }
              - { label: Body Font, name: body, widget: string }
              - { label: Designer Name, name: designer, widget: string }
              - { label: Designer Link, name: designerLink, widget: string }
      - label: Navigation
        name: navigation
        file: src/_data/navigation.json
        fields:
          - label: Items
            name: items
            widget: object
            fields:
              - { label: Title, name: name, widget: string }
