backend:
  name: git-gateway
  branch: main
media_folder: src/assets
public_folder: /assets

collections:
  - label: Content
    name: content
    files:
      - label: Home Page
        name: homepage
        file: src/index.md
        fields:
          - label: Intro
            name: intro
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
          - label: Activities
            name: activities
            widget: list
            fields:
              - { label: Activity, name: activity, widget: string }
              - { label: Short Title, name: short_title, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Summary, name: summary, widget: text }
              - { label: Text, name: text, widget: markdown }
          - label: About
            name: about
            widget: object
            fields:
              - { label: Text, name: text, widget: markdown }
          - label: Contact
            name: contact
            widget: object
            fields:
              - { label: Text, name: text, widget: markdown }
  - label: Settings
    name: settings
    files:
      - label: Meta Settings
        name: metaSettings
        file: src/_data/site.json
        fields:
          - { label: Site Name, name: name, widget: string }
          - { label: Meta Title, name: metaTitle, widget: string }
          - { label: Meta Description, name: metaDescription, widget: text }
          - { label: Canonical URL, name: url, widget: string }
          - { label: Favicon, name: favicon, widget: image }
